name: Deploy
on:
  push:
  pull_request:


jobs:
  downstream:
    name: Update an s3 bucket with recent production/stage tags
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Find out
      run: |
        env
        echo "${{ github.event.base_ref }}"
        #export MODEL=`cat $GITHUB_BASE_REF | gitops parse tag --model`
        #echo now you can deploy this $MODEL, upload it to s3, or do something else
